sources:
  habr:
    type: habr
    hubs:
      - id: artificial_intelligence
        slug: ИИ
      - id: circuit-design
        slug: Схем-ка
    rss_template: "https://habr.com/ru/rss/hubs/{hub_slug}/articles/?limit=100"
    initial_fetch_date: "2025-12-13 00:00:00"
    auto_update_within_days: 3
    display:
      article_meta:
        - rating
        - views
        - comments
        - bookmarks
